### ISSUE TITLE
improvements to new feature carousel

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight.io#335]
Loom overview: https://www.loom.com/share/34cea22256194b6db19c99aeacbf40e5

```[tasklist]
### Tasks
- [x] style of feature subtext is inconsistent with figma
- [x] style of feature 3-key-points with figma
- [ ] style of self-hosting code is inconsistent with figma
- [ ] https://github.com/highlight/highlight.io/issues/336
- [ ] https://github.com/highlight/highlight.io/issues/337
- [x] Feature images on mobile are all the same?
```
